language: node_js
node_js:
  - "iojs"
  - "6.10.3"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g karma-cli
  - npm install -g rollup
  - npm install
script:
  - npm test